BEGIN;

-- Seed AIRPORTS
INSERT INTO airports (code, city, country, timezone) VALUES
('BOM', 'Mumbai', 'India', 'Asia/Kolkata'),
('DEL', 'Delhi', 'India', 'Asia/Kolkata'),
('BLR', 'Bengaluru', 'India', 'Asia/Kolkata'),
('HYD', 'Hyderabad', 'India', 'Asia/Kolkata'),
('MAA', 'Chennai', 'India', 'Asia/Kolkata'),
('CCU', 'Kolkata', 'India', 'Asia/Kolkata'),
('PNQ', 'Pune', 'India', 'Asia/Kolkata'),
('AMD', 'Ahmedabad', 'India', 'Asia/Kolkata'),
('GOI', 'Goa', 'India', 'Asia/Kolkata'),
('COK', 'Kochi', 'India', 'Asia/Kolkata'),
('JAI', 'Jaipur', 'India', 'Asia/Kolkata'),
('SIN', 'Singapore', 'Singapore', 'Asia/Singapore'),
('KUL', 'Kuala Lumpur', 'Malaysia', 'Asia/Kuala_Lumpur'),
('BKK', 'Bangkok', 'Thailand', 'Asia/Bangkok'),
('HKG', 'Hong Kong', 'China', 'Asia/Hong_Kong'),
('HND', 'Tokyo', 'Japan', 'Asia/Tokyo'),
('SYD', 'Sydney', 'Australia', 'Australia/Sydney'),
('MEL', 'Melbourne', 'Australia', 'Australia/Melbourne'),
('DXB', 'Dubai', 'United Arab Emirates', 'Asia/Dubai'),
('DOH', 'Doha', 'Qatar', 'Asia/Qatar'),
('AUH', 'Abu Dhabi', 'United Arab Emirates', 'Asia/Dubai'),
('LHR', 'London', 'United Kingdom', 'Europe/London'),
('CDG', 'Paris', 'France', 'Europe/Paris'),
('FRA', 'Frankfurt', 'Germany', 'Europe/Berlin'),
('AMS', 'Amsterdam', 'Netherlands', 'Europe/Amsterdam'),
('ZRH', 'Zurich', 'Switzerland', 'Europe/Zurich'),
('FCO', 'Rome', 'Italy', 'Europe/Rome'),
('JFK', 'New York', 'United States', 'America/New_York'),
('SFO', 'San Francisco', 'United States', 'America/Los_Angeles'),
('LAX', 'Los Angeles', 'United States', 'America/Los_Angeles'),
('ORD', 'Chicago', 'United States', 'America/Chicago'),
('YYZ', 'Toronto', 'Canada', 'America/Toronto');

-- Seed AIRLINES
INSERT INTO airlines (code, name, country, is_preferred, corporate_discount) VALUES
('YA', 'Yash Air', 'India', TRUE, 18.0),
('AI', 'Air India Corporate', 'India', TRUE, 12.0),
('SG', 'Singapore Global', 'Singapore', TRUE, 14.0),
('EK', 'Emirates Connect', 'United Arab Emirates', FALSE, 10.0),
('QR', 'Qatar Connect', 'Qatar', TRUE, 11.0),
('BA', 'Britannia Airways', 'United Kingdom', FALSE, 8.0),
('LH', 'Deutsche Hansa', 'Germany', FALSE, 8.0),
('AF', 'Air Francais', 'France', FALSE, 7.0),
('UA', 'United Atlantic', 'United States', FALSE, 6.0),
('DL', 'Delta Skies', 'United States', TRUE, 9.0),
('JL', 'Japan Global', 'Japan', FALSE, 5.0),
('CX', 'Cathay Pacific', 'China', FALSE, 6.0);

-- Seed CITIES
INSERT INTO cities (city, country, currency, tier_multiplier) VALUES
('Mumbai', 'India', 'INR', 0.6),
('Delhi', 'India', 'INR', 0.6),
('Bengaluru', 'India', 'INR', 0.6),
('Hyderabad', 'India', 'INR', 0.5),
('Chennai', 'India', 'INR', 0.5),
('Kolkata', 'India', 'INR', 0.5),
('Pune', 'India', 'INR', 0.5),
('Ahmedabad', 'India', 'INR', 0.4),
('Goa', 'India', 'INR', 0.8),
('Kochi', 'India', 'INR', 0.5),
('Jaipur', 'India', 'INR', 0.5),
('Singapore', 'Singapore', 'SGD', 1.8),
('Kuala Lumpur', 'Malaysia', 'MYR', 0.7),
('Bangkok', 'Thailand', 'THB', 0.8),
('Hong Kong', 'China', 'HKD', 1.9),
('Tokyo', 'Japan', 'JPY', 2.0),
('Sydney', 'Australia', 'AUD', 1.8),
('Melbourne', 'Australia', 'AUD', 1.6),
('Dubai', 'United Arab Emirates', 'AED', 1.7),
('Doha', 'Qatar', 'QAR', 1.6),
('Abu Dhabi', 'United Arab Emirates', 'AED', 1.6),
('London', 'United Kingdom', 'GBP', 2.2),
('Paris', 'France', 'EUR', 2.0),
('Frankfurt', 'Germany', 'EUR', 1.6),
('Amsterdam', 'Netherlands', 'EUR', 1.8),
('Zurich', 'Switzerland', 'CHF', 2.5),
('Rome', 'Italy', 'EUR', 1.7),
('New York', 'United States', 'USD', 2.5),
('San Francisco', 'United States', 'USD', 2.4),
('Los Angeles', 'United States', 'USD', 2.2),
('Chicago', 'United States', 'USD', 1.9),
('Toronto', 'Canada', 'CAD', 1.8);

COMMIT;
